### ISSUE TITLE
Error uploading GeoJson to MapBox

### ISSUE THREAD

**Issue by akreider** [reclaimphiladelphia/reclaim_map#13]
When I upload the geojson data that is in the project to MapBox Studio -- I get an error message (something like invalid type).

**Comment by aerispaha** [comment]
I can upload geojson files by logging into my account, navigating to [mapbox.com/studio/tilesets/](https://www.mapbox.com/studio/tilesets/), clicking "New tileset":
![image](https://user-images.githubusercontent.com/6521360/41634489-fc9f8dfc-7411-11e8-9720-dfde9c344ea1.png)

and then dragging/dropping this (uzipped) geojson file in this attached zip:
[divisions_cp.zip](https://github.com/reclaimphiladelphia/reclaim_map/files/2117602/divisions_cp.zip)

Give that a try in the reclaim Philly mapbox account, and let me know if it still doesn't work for you.

**Comment by akreider** [comment]
I try that file. I get "Zip file did not contain a shp file".
I have got other files to work.

**Comment by akreider** [comment]
I tried it twice.  The upload works, but then I get "ZIP file did not contain a shp file".

**Comment by akreider** [comment]
Ok finally got it to work. Unzipped that divisions_cp.zip and then uploaded it.  (When you said uzip - I thought you might be using a program called uzip - like I use 7zip sometimes.  But I'm guessing you meant unzip). 

I think I was previously using a bad version of the geojson (maybe from the main branch before it forked?)

**Comment by aerispaha** [comment]
@akreider, NICE WORK. glad this has been figured out
