### ISSUE TITLE
Naming our data sources in MapBox

### ISSUE THREAD

**Issue by akreider** [reclaimphiladelphia/reclaim_map#18]
What is the best way to name our data sources in MapBox? 

I'd like to include the year and layer name in a standard format that is easy to remember.

For instance, we are currently using layers like: 'divisions_cp_2018-28546a'

I'm also not sure how to change the name using MapBox.

**Comment by aerispaha** [comment]
It seems like the trailing "-28546a" in the Mapbox resource "divisions_cp_2018-28546a" is added automatically. I'm not sure if we can control that (hopefully we can). Either way I'm down for a standardized naming convention to keep things clean. Feel free to suggest a convention in this issue!
