### ISSUE TITLE
Toggle map layers

### ISSUE THREAD

**Issue by aerispaha** [reclaimphiladelphia/reclaim_map#4]
Add the ability to toggle map layers on and off in the map with a simple HTML UI control. For example, in the current map prototype, we should be able to turn off/on the Ward polygons. 

As we scale up this project, we'll need to be able to easily add new layers to the map with this toggle functionality. Given this, this function should accept an variable number of layers (probably in an array or something similar). 

The solution doesn't need to be the most elegant, just needs to be a reasonably modular first cut. It also isn't important that the UI control be nice looking at this point.

**Comment by akreider** [comment]
https://www.mapbox.com/mapbox-gl-js/example/toggle-layers/
