### ISSUE TITLE
Project Name / Branding - what is this project called?

### ISSUE THREAD

**Issue by aerispaha** [reclaimphiladelphia/reclaim_map#8]
### Project Name and Available Domains
This project was temporarily called "Coalition Map", at a time when this was thought to be more of a collaboration between Reclaim and other orgs. We never settled on that name, though, and Lev asked us to come up with something more inspiring "that will hit people more in the gut". 

### Criteria 
The name of this project should try to reflect its intended mission: to educate people on their local political environment, politicize people, organize people, and lower the barrier of entry to activism and local politics.  Whatever name we select should probably meet the following criteria:  
- able to secure the ".org" domain name
- is easy to say and not  too jargony
- domain name is relatively short
- inspiring and hits people in the gut

### Past Work/Attempts 
Several months ago, I spent some time thinking about this and researching which URLs are available. My favorite ideas at the time were:

- **electlocal.org** - seems to make sense for the application, is snappy, concise, versatile, and can be a play on the "buy local" campaigns (though now I'm frustrated with this because I think it should be "buy/elect localLY"
- **blocksunited.org** - has local, spatial, on-my-block, corner store, non-atomized connotations which makes sense
- **localalliance.org** - is cool, but seems like it might not totally fit for this purpose

### Task Goal
- come up with a good name for this project that is endorsed by Reclaim lead organizers. 
- if necessary, create a poll on which we can vote for the final option

**Comment by aerispaha** [comment]
Other options that were brainstormed about 6 months ago that were available at the time:
- [powerposition.org](http://powerposition.org/) - how is local power positioned. maybe too abstract
- [powershed.org](http://powershed.org/) - like a watershed, only for local power characteristics. I like this, but it just makes me think of a tool shed.
- [powerblocks.org](http://powerblocks.org/)
- [powerneighbor.org](http://powerneighbor.org/)
- [wardpower.org](http://wardpower.org/) - I like this, but "ward" may be too jargony  
- [wardalliance.org](http://wardalliance.org/)
- [neighborleaders.org](http://neighborleaders.org/)
- [citizenelect.org](http://citizenelect.org/)
- [localelect.org](http://localelect.org/)
- [blockleaders.org](http://blockleaders.org/)
- [localelective.org](http://localelective.org/)
- [insurgantelector.org](http://insurgantelector.org/)
- [localinfluence.org](http://localinfluence.org/)
- [communityelect.org](http://communityelect.org/)
- [democraticlocal.org](http://democraticlocal.org/)
- [commonpower.org](http://commonpower.org/) - cool URL, but I feel like this should be used for another grass-roots project
- [localreps.org](http://localreps.org/)
- [blockrep.org](http://blockrep.org/), [blockreps.org](http://blockreps.org/)
- [civilblock.org](http://civilblock.org/)
- [neighboralliance.org](http://neighboralliance.org/)

**Comment by akreider** [comment]
Lots of good ideas.  Do we want a Philly theme?

We could end up with a generic project that any city could use and then a Philly specific one (if we go the ambitious route) - and then want two domains.

**Comment by aerispaha** [comment]
@akreider we could do a Philly theme. I think I was originally hoping for something that could be generalized so other communities/cities could use it. This actually makes me think of using "Reclaim" in the name.

here's a few on that riff with available domains:
- **reclaimcity.org** - concise, has spatial, grassroots vibes
- **reclaimlocal.org** - concise, has spatial, grassroots vibes
- **reclaimvillage.org** - ditto
- **reclaimmap.org** - super concise, I just don't like the double "m" 

Here's a Philly theme:
- **phillyatlas.org** - I think i like this a lot


Another option, I suppose, is to just host this within the reclaimphiladelphia.org url. It's just sort of a long url as it is: 
- reclaimphiladelphia.org/map

**Comment by aerispaha** [comment]
Need to get buy in and feedback from lead organizers

**Comment by aerispaha** [comment]
reclaimatlas.org

**Comment by aerispaha** [comment]
Based on feedback from @jfrankl and James, we'll keep this project branded under the Reclaim Philadelphia, refer to it as "Reclaim Map" and keep it at the current url: [reclaimphiladelphia.github.io/reclaim_map](https://reclaimphiladelphia.github.io/reclaim_map/)
